### PR TITLE
Migrate to Bootstrap 3

### PR DESCRIPTION
**Pull request by benjie**
:warning: In progress; do not merge.

@jlowe64 turns out that migrating to Bootstrap 3 was a little more complex than we thought; basically all the formatting is broken.

I started working through the changes outlined in http://getbootstrap.com/migration/ but it's not exhaustive and some of the migrations aren't immediately clear. Many of the forms are currently still broken formatting. I've rolled back to the last release and opened this as a work in progress branch.

### CODE REVIEW

**Comment by jlowe64** [comment]
Yes, indeed. I am currently going through the theme fixing all those things as I noticed some design issues. I'm just doing a basic readjustment of some of the styling and layout while I'm in there.

**Comment by jlowe64** [comment]
It would help me if you could update the pg dependency issue if you have the time. It'll allow me to be a bit more portable with my Dev environment as its a bit unpredictable at the moment if I'll be able to launch it on any given platform.

**Comment by benjie** [comment]
@jlowe64 I literally just merged that (including extending CI support to Node 4 and 5) - #47 :)

You may want to merge some of my changes above into your work. Good luck!

**Comment by benjie** [comment]
@jlowe64 I've added you as a collaborator so you can take over this branch if you like :smile: 

Next thing for me to do is to implement the password reset functionality!

**Comment by jlowe64** [comment]
Very cool! Thank you for doing that. I'll merge them into my fork asap. :D 

I'll also keep working on my theme changes. I'm gonna rewrite some of the jade because I've seen some better ways to manage the themes, if you don't mind. :)

**Comment by benjie** [comment]
By all means; AFAIK there's only one theme plugin in use (the SMI one); did you know you can toggle between themes quickly in the settings page?

**Comment by jlowe64** [comment]
No, I didn't.. that sorta changes some things. Are we talking creating a sub-theme of the default or being able to totally theme the layout differently? Where would this second theme be located?

**Comment by benjie** [comment]
https://github.com/somakeit/members-area-theme-somakeit

screenshot 2016-03-16 11 31 28


I extended Jade's extends syntax adding a bang (`!`) prefix so that `extends !layout` means "extend the built in layout template"; so templates can replace blocks within the built in layout without replacing everything. If a template doesn't define a particular view then the built in one is used instead. The So Make It theme just mods the layout to adjust the page title, add a couple links to the header bar and add some details to the footer - nothing major. It also defines a few extra styles; but again the `@import members` in [style.styl](https://github.com/somakeit/members-area-theme-somakeit/blob/master/public/css/style.styl) just re-imports the built in styles which are then extended via the somakeit.styl file.

**Comment by jlowe64** [comment]
So it looks like some of the adjustments I'm doing is gonna make the default layout a little bit nicer, so I'll keep going in the direction I'm going but focus a lot more on making the conversion from bootstrap 2 to 3 a priority. When it comes time to brand our version, I'll go for a sub-theme in the method you describe.

**Comment by jlowe64** [comment]
@benjie I've made a whole lot of changes. I know I've probably missed some things. Firstly, I probably need to limit the width of the fields, but I'd like some advice on what you feel is best in that area. Secondly, I'm sure there's some design adjustments I need to make, but I'm confident I'm going in a good direction. 

If you wanted, could you possibly take a look at the adjustments and let me know if there's anything glaring?

**Comment by benjie** [comment]
Excellent work! Okay, so here's a list of the issues I've spotted (don't be disheartened; the majority is done now!)

### Main layout

There's an issue with `#main` - it has a margin-left of `250px` which is causing loads of stuff to flow off the right of the screen. Just twiddling in the developer console I can fix this by adding `margin: 0; padding: 0 30px 0 280px` to `#main.container` within the min 768 media query:

screenshot 2016-03-21 09 18 51

### Social login

screenshot 2016-03-21 09 03 56

Need to fix it in the [members-area-passport plugin's index.coffee:107](https://github.com/members-area/members-area/blob/411fa5db6c0c86ee0b3415d09806fbbe11d609a6/plugins/members-area-passport/index.coffee#L107) - specifically replace `".login-form h2"` with whatever is relevant now.

### Themes

The theme header/footer is no longer being overridden by the So Make It theme; I'm guessing this is due to splitting out the navigation header and footer into their own files; so this is hopefully something I can easily fix in the theme itself (and am happy to do so)

### Nav sidebar

screenshot 2016-03-21 09 11 17

It's somewhat large now; I've not tested on mobile but we use it on mobile a lot so having it more condensed on mobile at least would be appreciated. The headers could do with some styling (perhaps restore the text-transform and bold?) and there's no need for the gap at the top

### Inputs

screenshot 2016-03-21 09 13 19


Some inputs are wider than the screen itself, especially in the Settings section.

UPDATE: I think this is due to the main layout issue outlined above

### Dashboard

screenshot 2016-03-21 09 14 45

Similar to inputs, possibly, the text could do with some right padding. 

UPDATE: I think this is due to the main layout issue outlined above

### Footer clearfix

screenshot 2016-03-21 09 21 33


Footer seems to need a clearfix or similar - it should go below both the content and the sidebar

### Radio inputs 100% width

screenshot 2016-03-21 09 22 28

(Previously:
screenshot 2016-03-21 09 23 07
)


Probably don't want this :wink: 

### Profile plugins

screenshot 2016-03-21 09 28 44


None of the plugins are successfully adding things to the profile page. Affected are:

- "Manage PIN Code"
- "Add a Payment"
- "Payments" (same plugin?)
- "Manage RFID tags"

**Comment by benjie** [comment]
@jlowe64 I'm happy to help you fix some of these of an evening; let me know if you want to pair on any of it over ScreenHero.

**Comment by jlowe64** [comment]
@benjie Thank you for going through it! This looks great. I can get on this tonight. Hopefully we can wrap this up this week. 

I'll get back to you on my availability for paired programming, that sounds really neat.

**Comment by jlowe64** [comment]
Hmmmmm, not sure why it failed to load the banking plugin...

**Comment by benjie** [comment]
Weird. I'll rebuild since it was only one fail out of 12!

**Comment by jlowe64** [comment]
Ahh that worked. Okay, so I have a bit more to do. I need to consider the mobile site, and work on styling some of the forms to your specifications.

**Comment by benjie** [comment]
Looks like a great start though :smile:

**Comment by jlowe64** [comment]
@benjie Do you prefer the menu load collapsed or not on mobile? Currently I have it loading open when you are in the menu system, showing which page you're currently on using the active class. You then may collapse if you like.

**Comment by jlowe64** [comment]
I have updated some of the mobile look and feel. 

Getting a potential jquery load error on `/roles/applications.` Not sure what's going on. Any hints?

**Comment by benjie** [comment]
@jlowe64 as regards expand/collapse: whatever works best. As for the jQuery error, no clue - send a screenshot of the page + devtools' console view

**Comment by jlowe64** [comment]
image

It complains about the `metisMenu` function, but if I remove the function, it then starts complaining about jQuery stuff. This is the only page it happens on.

**Comment by benjie** [comment]
Adventure Time! :metal: 

I don't believe we've explicitly used metisMenu anywhere on that page, so my guess would be it's a dependency of the old bootstrap and needs to be hunted out 🔍  and destroyed 🔥 

Have a look through the network panel and ensure that the only JavaScript being loaded is that which you'd expect (i.e. bootstrap 3) - if there's any old stuff leaking through you'll want to eradicate it. Assuming everything's up to date then maybe there's a missing dependency (i.e. metisMenu isn't being loaded) or maybe they're being loaded in the wrong order (i.e. metisMenu needs to be loaded after jQuery but before whatever uses it).

Good luck!

**Comment by jlowe64** [comment]
I've removed the bits that started chatting about "metisMenu" I've removed everything except the logic which opens and closes the menu on mobile. 

It's still throwing me the following error only when I reopen the menu:

```
bootstrap.min.js:6 Uncaught TypeError: Cannot read property 'height' of undefined
d.show	@	bootstrap.min.js:6
d.toggle	@	bootstrap.min.js:6
d	@	bootstrap.min.js:6
(anonymous function)	@	bootstrap.min.js:6
n.extend.each	@	jquery-2.2.3.min.js:2
n.fn.n.each	@	jquery-2.2.3.min.js:2
c	@	bootstrap.min.js:6
(anonymous function)	@	bootstrap.min.js:6
n.event.dispatch	@	jquery-2.2.3.min.js:3
r.handle	@	jquery-2.2.3.min.js:3

```

I'm kinda at a loss how to debug this. The current commit has me pulling the newest versions of jQuery and Bootstrap from CDN or downloaded new copies. Still get the error. In `members.js` I've fixed the JS so that it reports back the height that the menu should be, but I guess I'm just totally missing something.

**Comment by benjie** [comment]
Just a thought, but are

```jade
    script(src='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js')
    script(src='//cdnjs.cloudflare.com/ajax/libs/metisMenu/2.5.0/metisMenu.min.js')
```
in the wrong order - i.e. do you need to load metisMenu before you load bootstrap itself?

**Comment by benjie** [comment]
I don't think `members.js` has anything to do with this issue - it seems to be jquery dispatching a click event which goes via bootstrap.js and then tries to show a particular element for some reason; and shopwing that element (possibly a callback for it?) triggers the error due to trying to access `height` on an undefined property or variable. I'd need to see it in a debugger to figure it out for sure.

**Comment by jlowe64** [comment]
Could be, I'll definitely switch them around. But, they aren't being used in the current iteration because I wanted to see what the problem with bootstrap/jquery were first. 

I am getting undefined on the sidebar classes. someone attempted `item.className` but there doesn't seem to be a value for that. I tried `item.classNames` and also tried to print out the object contents, but neither of those yielded anything.

But, I dunno if that would have been anything to do with the issue.

**Comment by benjie** [comment]
If you've got a bit of time let's ScreenHero tonight and go through it together. Call me when you're free.

**Comment by jlowe64** [comment]
Unfortunately, I am in a pub GMing an RPG! I might be able to do it tomorrow, but it would be late-ish because I have to go to Gatwick to pick up my lost iPad. :P I swear I'm not normally this busy. If you're okay with late-ish tomorrow, then we could potentially do it then, or Thursday.

**Comment by benjie** [comment]
Sure; you've got my number just give me a ring when you're free 😀

**Comment by benjie** [comment]
screenshot 2016-05-01 12 20 50

**Comment by benjie** [comment]
screenshot 2016-05-01 12 22 22

**Comment by jlowe64** [comment]
I’ve run those updates, removed metisMenu all together as I saw it as duplicate functionality and bootstrap3 is just fine for our uses. This should be ready to merge as soon as checks are passed.

**Comment by benjie** [comment]
Merged! 🌟

**Comment by jlowe64** [comment]
Yayyyyyyyy so exciting.

**Pull request merged**
